FROM apache/airflow:2.10.2

# Install system dependencies
USER root
RUN apt-get update && apt-get install -y build-essential cmake

# Switch to Airflow user
USER airflow

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        feedparser==6.0.10 \
        beautifulsoup4==4.12.2 \
        requests==2.31.0 \
        pinecone==5.4.0 \
        sentence-transformers==3.3.0 \
        huggingface-hub==0.23.2 \
        transformers==4.41.0 \
        python-dotenv \
        rapidfuzz==2.15.1 \
        boto3 \
        openai==0.28
