name: CI/CD Pipeline for FastAPI, Streamlit, and Airflow

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify your Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      - name: Install dependencies for FastAPI
        working-directory: Application
        run: |
          poetry install --no-dev

      - name: Build and push FastAPI Docker image
        working-directory: Application
        run: |
          docker build -t gcr.io/bigdata-3-440404/fastapi-app -f Dockerfile.fastapi .
          docker push gcr.io/bigdata-3-440404/fastapi-app

      - name: Install dependencies for Streamlit
        working-directory: Application
        run: |
          poetry install --no-dev  # Ensure Streamlit dependencies are included

      - name: Build and push Streamlit Docker image
        working-directory: Application
        run: |
          docker build -t gcr.io/bigdata-3-440404/streamlit-app -f Dockerfile.streamlit .
          docker push gcr.io/bigdata-3-440404/streamlit-app

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: bigdata-3-440404
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Use the secret you created
          export_default_credentials: true

      - name: Deploy FastAPI to Cloud Run
        run: |
          gcloud run deploy fastapi-service --image gcr.io/bigdata-3-440404/fastapi-app --platform managed --region us-central1 --allow-unauthenticated

      - name: Deploy Streamlit to Cloud Run
        run: |
          gcloud run deploy streamlit-service --image gcr.io/bigdata-3-440404/streamlit-app --platform managed --region us-central1 --allow-unauthenticated
